#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

local_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$local_branch" = "main" ]; then
  echo "You are on main branch. Please create a new branch and commit your changes there."
  exit 1
fi
valid_branch_regex="^(build|chore|ci|docs|feat|fix|test)\/[a-zA-Z0-9._-]+$"
if [[ ! $local_branch =~ $valid_branch_regex ]]; then
  echo "Your branch name is not valid. Please use one of the following patterns:"
  echo "  - build/..."
  echo "  - chore/..."
  echo "  - ci/..."
  echo "  - docs/..."
  echo "  - feat/..."
  echo "  - fix/..."
  echo "  - test/..."
  exit 1
fi
